### Numpy --> Play with Arrays (Numbers)
### pandas --> Dataset
### Matplotlib --> Data Visualization
### Seaborn --> Data Visualization
### Scipy --> Statistical
### Sklearn --> Algorithm

# Numpy: Package for Multidimensional array

In [1]:
import numpy as np

In [2]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [6]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
np.arange(1,36,5)

array([ 1,  6, 11, 16, 21, 26, 31])

In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [17]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [18]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [19]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(3,5)

array([[0.4810722 , 0.77416051, 0.40185032, 0.32039578, 0.62794011],
       [0.66025479, 0.84019927, 0.29392611, 0.06321902, 0.23655865],
       [0.07344116, 0.31908986, 0.51830945, 0.62248196, 0.18790781]])

In [21]:
arr=np.random.randn(2,4)
arr

array([[ 0.29770907, -0.36439951, -1.03075786,  0.71425762],
       [-0.59423899, -0.08553221,  0.6370976 , -0.1987079 ]])

In [22]:
np.random.randint(2,100)

66

In [23]:
np.random.randint(20,56,100)

array([32, 41, 31, 49, 22, 37, 48, 51, 45, 49, 20, 38, 25, 49, 55, 49, 32,
       20, 52, 49, 27, 48, 26, 39, 45, 55, 22, 40, 30, 26, 54, 24, 44, 50,
       29, 27, 44, 39, 51, 21, 35, 53, 52, 41, 24, 36, 22, 51, 55, 38, 54,
       40, 39, 20, 31, 55, 20, 29, 36, 43, 45, 37, 54, 31, 20, 28, 28, 44,
       35, 49, 29, 25, 24, 33, 48, 44, 44, 41, 31, 45, 23, 28, 22, 34, 38,
       37, 54, 39, 26, 54, 43, 46, 46, 29, 20, 49, 26, 34, 30, 32])

In [25]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [26]:
rand_array=np.random.randint(0,10,50)
rand_array

array([1, 8, 6, 7, 0, 9, 3, 9, 6, 5, 6, 4, 2, 0, 7, 5, 4, 3, 9, 1, 7, 5,
       9, 1, 7, 8, 2, 5, 7, 8, 6, 0, 9, 8, 2, 0, 4, 1, 5, 0, 5, 1, 7, 3,
       3, 6, 1, 6, 3, 3])

In [27]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [28]:
sample_array.reshape(4,3)

ValueError: cannot reshape array of size 30 into shape (4,3)

In [29]:
rand_array.max()

9

In [30]:
rand_array.min()

0

In [31]:
rand_array.argmax()

5

In [32]:
rand_array.argmin()

4

In [34]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
a=np.random.rand(2,3)
a

array([[0.45333442, 0.30524981, 0.87958729],
       [0.67618281, 0.02898312, 0.45546708]])

In [38]:
a.T

array([[0.45333442, 0.67618281],
       [0.30524981, 0.02898312],
       [0.87958729, 0.45546708]])

In [39]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [40]:
sample_array[0]

10

In [41]:
sample_array[2:5]

array([12, 13, 14])

In [42]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [43]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [44]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [45]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [46]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

# Two-Dimensional array

In [48]:
import numpy as np

In [50]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [51]:
sample_matrix[1,2]


21

In [52]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [53]:
sample_matrix[2]

array([56, 76, 24,  7])

In [55]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [57]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [62]:
sample_matrix[1,(1,2)]

array([23, 21])

# Selection Technique

In [ ]:
sample_array=np.arange(1,20)

In [63]:
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20])

In [64]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [65]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [66]:
np.exp(sample_array) # exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [67]:
np.sqrt(sample_array) # square root

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [68]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [69]:
np.max(sample_array)

19

In [70]:
np.min(sample_array)

1

In [71]:
np.argmax(sample_array)

18

In [72]:
np.argmin(sample_array)

0

In [73]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [74]:
np.std(sample_array) # standard diviation

5.477225575051661

In [75]:
np.var(sample_array) # varients

30.0

In [76]:
np.mean(sample_array)

10.0

In [77]:
array=np.random.randn(3,4)
array

array([[ 0.17871029,  0.46964834,  0.17841992, -0.20121273],
       [-1.01684642, -0.45893753, -1.03379701,  0.93313145],
       [-0.80251119, -1.19600881,  0.34354149,  0.79571427]])

In [78]:
np.round(array,decimals=2)

array([[ 0.18,  0.47,  0.18, -0.2 ],
       [-1.02, -0.46, -1.03,  0.93],
       [-0.8 , -1.2 ,  0.34,  0.8 ]])

In [79]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

### Pandas

In [80]:
import pandas as pd
import numpy as np

# Pandas dataframe and indexing

In [81]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [83]:
sports1["football"]

2

In [84]:
sports2=pd.Series([11,2,3,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football     2
baseball     3
golf         4
dtype: int64

In [85]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football       4.0
golf           8.0
dtype: float64

In [87]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.365251  0.995388  0.070235  0.781244  0.457395
B  0.779308  0.133213  0.179311  0.803600  0.124645
C  0.083141  0.730238  0.768455  0.171324  0.053123
D  0.560614  0.934606  0.534136  0.101560  0.446657
E  0.468541  0.592519  0.353384  0.594877  0.377387
F  0.278223  0.389662  0.188287  0.403837  0.224658
G  0.789667  0.049059  0.460287  0.966924  0.048619
H  0.522434  0.790270  0.999738  0.898884  0.886052

In [88]:
df1["Score1"]

A    0.365251
B    0.779308
C    0.083141
D    0.560614
E    0.468541
F    0.278223
G    0.789667
H    0.522434
Name: Score1, dtype: float64

In [89]:
df1[['Score1','Score2']] 

Score1    Score2
A  0.365251  0.995388
B  0.779308  0.133213
C  0.083141  0.730238
D  0.560614  0.934606
E  0.468541  0.592519
F  0.278223  0.389662
G  0.789667  0.049059
H  0.522434  0.790270

In [90]:
df1['Score6']=df1['Score1']+df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.365251  0.995388  0.070235  0.781244  0.457395  1.360639
B  0.779308  0.133213  0.179311  0.803600  0.124645  0.912522
C  0.083141  0.730238  0.768455  0.171324  0.053123  0.813379
D  0.560614  0.934606  0.534136  0.101560  0.446657  1.495220
E  0.468541  0.592519  0.353384  0.594877  0.377387  1.061060
F  0.278223  0.389662  0.188287  0.403837  0.224658  0.667884
G  0.789667  0.049059  0.460287  0.966924  0.048619  0.838725
H  0.522434  0.790270  0.999738  0.898884  0.886052  1.312705

In [93]:
df2={'ID':['101','102','103','107','176'],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
3  107  Kavin      87
4  176  Lally     123

In [94]:
df['ID']

0    101
1    102
2    103
3    107
4    176
Name: ID, dtype: object

In [97]:
df[['ID','Name']]

ID   Name
0  101   John
1  102  Mercy
2  103  Akash
3  107  Kavin
4  176  Lally