### Numpy --> Play with Arrays (Numbers)
### pandas --> Dataset
### Matplotlib --> Data Visualization
### Seaborn --> Data Visualization
### Scipy --> Statistical
### Sklearn --> Algorithm

# Numpy: Package for Multidimensional array

In [10]:
import numpy as np

In [11]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [12]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [13]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [16]:
np.arange(1,36,5)

array([ 1,  6, 11, 16, 21, 26, 31])

In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [22]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [24]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [25]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [26]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [27]:
np.random.rand(3,5)

array([[0.75224841, 0.52170887, 0.74535219, 0.54818621, 0.92324836],
       [0.75488577, 0.12579793, 0.71100776, 0.97042543, 0.81688902],
       [0.06699567, 0.45794385, 0.01728201, 0.03238039, 0.12134095]])

In [28]:
arr=np.random.randn(2,4)
arr

array([[ 1.41782395, -0.37528382,  0.62986406, -0.49358813],
       [-0.87895493,  0.1130793 ,  0.19250935, -0.85478546]])

In [29]:
np.random.randint(2,100)

28

In [30]:
np.random.randint(20,56,100)

array([55, 33, 54, 47, 30, 42, 23, 21, 39, 34, 29, 39, 47, 42, 29, 29, 29,
       24, 40, 28, 39, 50, 49, 36, 30, 36, 20, 54, 45, 41, 33, 54, 48, 21,
       48, 29, 41, 43, 31, 24, 41, 28, 29, 48, 32, 24, 32, 30, 54, 35, 31,
       41, 34, 39, 51, 20, 47, 45, 51, 25, 24, 53, 36, 45, 38, 30, 25, 47,
       53, 35, 46, 46, 52, 51, 36, 44, 35, 33, 34, 43, 42, 43, 45, 31, 31,
       53, 28, 33, 26, 24, 29, 39, 32, 48, 41, 24, 31, 32, 33, 21])

In [31]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [32]:
rand_array=np.random.randint(0,10,50)
rand_array

array([8, 4, 5, 2, 3, 7, 3, 2, 0, 1, 6, 4, 2, 7, 1, 1, 0, 7, 4, 0, 2, 7,
       9, 4, 0, 7, 3, 5, 3, 0, 5, 9, 2, 5, 9, 4, 9, 7, 6, 6, 3, 2, 9, 9,
       0, 9, 7, 1, 9, 3])

In [33]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [34]:
sample_array.reshape(4,3)

ValueError: cannot reshape array of size 30 into shape (4,3)

In [35]:
rand_array.max()

9

In [36]:
rand_array.min()

0

In [37]:
rand_array.argmax()

22

In [38]:
rand_array.argmin()

8

In [39]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
a=np.random.rand(2,3)
a

array([[0.04124511, 0.64118751, 0.39618135],
       [0.23367708, 0.18318181, 0.21255308]])

In [42]:
a.T

array([[0.04124511, 0.23367708],
       [0.64118751, 0.18318181],
       [0.39618135, 0.21255308]])

In [43]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [44]:
sample_array[0]

10

In [45]:
sample_array[2:5]

array([12, 13, 14])

In [46]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [47]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [48]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [49]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [50]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

# Two-Dimensional array

In [51]:
import numpy as np

In [52]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [53]:
sample_matrix[1,2]


21

In [54]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [55]:
sample_matrix[2]

array([56, 76, 24,  7])

In [56]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [57]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [58]:
sample_matrix[1,(1,2)]

array([23, 21])

# Selection Technique

In [59]:
sample_array=np.arange(1,20)

In [60]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [61]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [62]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [63]:
np.exp(sample_array) # exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [64]:
np.sqrt(sample_array) # square root

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [65]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [66]:
np.max(sample_array)

19

In [67]:
np.min(sample_array)

1

In [68]:
np.argmax(sample_array)

18

In [69]:
np.argmin(sample_array)

0

In [70]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [71]:
np.std(sample_array) # standard diviation

5.477225575051661

In [72]:
np.var(sample_array) # varients

30.0

In [73]:
np.mean(sample_array)

10.0

In [74]:
array=np.random.randn(3,4)
array

array([[-1.05759002, -0.79577045, -0.98539719,  0.01548581],
       [-1.2417425 ,  0.30107   ,  0.43113968, -1.87709664],
       [-2.12048481,  0.6862392 , -2.3048441 ,  0.06452795]])

In [75]:
np.round(array,decimals=2)

array([[-1.06, -0.8 , -0.99,  0.02],
       [-1.24,  0.3 ,  0.43, -1.88],
       [-2.12,  0.69, -2.3 ,  0.06]])

In [76]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

### Pandas

In [77]:
import pandas as pd
import numpy as np

# Pandas dataframe and indexing

In [78]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [79]:
sports1["football"]

2

In [80]:
sports2=pd.Series([11,2,3,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football     2
baseball     3
golf         4
dtype: int64

In [81]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football       4.0
golf           8.0
dtype: float64

In [82]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.147142  0.974877  0.295385  0.594198  0.174168
B  0.120291  0.527685  0.203709  0.217374  0.270098
C  0.125881  0.288742  0.871942  0.175374  0.698536
D  0.289725  0.330064  0.371583  0.145037  0.916128
E  0.162388  0.373080  0.972119  0.527103  0.419850
F  0.325277  0.146297  0.858636  0.968373  0.534876
G  0.015348  0.299399  0.281948  0.429839  0.815658
H  0.818710  0.528124  0.357970  0.989152  0.898625

In [83]:
df1["Score1"]

A    0.147142
B    0.120291
C    0.125881
D    0.289725
E    0.162388
F    0.325277
G    0.015348
H    0.818710
Name: Score1, dtype: float64

In [84]:
df1[['Score1','Score2']] 

Score1    Score2
A  0.147142  0.974877
B  0.120291  0.527685
C  0.125881  0.288742
D  0.289725  0.330064
E  0.162388  0.373080
F  0.325277  0.146297
G  0.015348  0.299399
H  0.818710  0.528124

In [85]:
df1['Score6']=df1['Score1']+df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.147142  0.974877  0.295385  0.594198  0.174168  1.122019
B  0.120291  0.527685  0.203709  0.217374  0.270098  0.647976
C  0.125881  0.288742  0.871942  0.175374  0.698536  0.414623
D  0.289725  0.330064  0.371583  0.145037  0.916128  0.619790
E  0.162388  0.373080  0.972119  0.527103  0.419850  0.535468
F  0.325277  0.146297  0.858636  0.968373  0.534876  0.471574
G  0.015348  0.299399  0.281948  0.429839  0.815658  0.314747
H  0.818710  0.528124  0.357970  0.989152  0.898625  1.346834

In [86]:
df2={'ID':['101','102','103','107','176'],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
3  107  Kavin      87
4  176  Lally     123

In [87]:
df['ID']

0    101
1    102
2    103
3    107
4    176
Name: ID, dtype: object

In [88]:
df[['ID','Name']]

ID   Name
0  101   John
1  102  Mercy
2  103  Akash
3  107  Kavin
4  176  Lally

In [89]:
df=df.drop("ID",axis=1)

In [90]:
df

Name  Profit
0   John      20
1  Mercy      54
2  Akash      56
3  Kavin      87
4  Lally     123

In [91]:
df.drop(3)

Name  Profit
0   John      20
1  Mercy      54
2  Akash      56
4  Lally     123